# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  lint_code:
    executor: node/default
    description: Lint Code
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Lint Code
          command: npm run lint:fix
  build:
    executor: node/default
    description: Build
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Build
          command: npm run build
  run_release:
    executor: node/default
    description: Release
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Set up git
          command: |
            git config --global user.email $GIT_EMAIL
            git config --global user.name $GIT_NAME
      - run:
          name: Run release
          command: npm run release
  publish_to_npm:
    executor: node/default
    description: Publish to npm
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Login to npm
          command: echo "//registry.npmjs.org/:authToken=${NPM_TOKEN}" > ~/.npmrc
      - run:
          name: Publish to npm
          command: npm publish
          enviroment:
            NPM_TOKEN: $NPM_TOKEN

workflows:
  build_app:
    jobs:
      - lint_code
      - build:
          requires:
            - lint_code
      - run_release:
          requires:
            - build
      - publish_to_npm:
          requires:
            - run_release
